[package]
name = "examples"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
identity = { path = "../identity", features = ["account", "stronghold"] }
pretty_env_logger = { version = "0.4" }
rand = { version = "0.8" }
tokio = { version = "1.17.0", features = ["full"] }

[[example]]
name = "getting_started"
path = "getting_started.rs"

[[example]]
name = "create_did"
path = "basic/1_create_did.rs"

[[example]]
name = "config"
path = "basic/8_config.rs"

[[example]]
name = "manipulate_did"
path = "basic/2_manipulate_did.rs"

[[example]]
name = "lazy"
path = "basic/9_lazy.rs"

[[example]]
name = "signing"
path = "basic/7_signing.rs"

[[example]]
name = "multiple_identities"
path = "basic/6_multiple_identities.rs"

[[example]]
name = "unchecked"
path = "advanced/3_unchecked.rs"

[[example]]
name = "create_vc"
path = "basic/3_create_vc.rs"

[[example]]
name = "create_vp"
path = "basic/4_create_vp.rs"

[[example]]
name = "resolve_history"
path = "advanced/2_resolve_history.rs"

[[example]]
name = "key_exchange"
path = "advanced/1_key_exchange.rs"

[[example]]
name = "revoke_vc"
path = "basic/5_revoke_vc.rs"
