name: 'private-tangle-setup'
description: 'Setup a private tangle'
runs:
  using: "composite"
  steps:
    - name: Setup private tangle
      shell: bash
      run: |
        git clone https://github.com/iotaledger/hornet.git
        cd hornet/private_tangle
        sudo ./cleanup.sh
        sudo ./bootstrap.sh
        sudo ./run.sh -d
